### ISSUE TITLE
Add Sass to project

### ISSUE THREAD

**Issue by LionOnTheWeb** [OLLEO-DIGITAL/Jervis-Tetch#17]
# Overview
As a developer, I want to be able to use sass efficiently in this project to be able to access advanced features for styling.

# Tasks
- [x] Add sass dependency to project `yarn add -D sass`
- [x] Create styles directory in `src/lib/styles` and add the following sub-directories
    - [x] `base/`
    - [x] `global/`
    - [x] `utils/`
- [x] Config SvelteKit to include path to allow us to use shorter import definitions
    - be able to use `@import or @use 'base/typography'` vs `@import or @use '.src/lib/styles/base/typography'` 
- [x] Initialize the following files in the new directory

```
src
    lib
        styles
            base
                breakpoints.scss
                colors.scss
                typography.scss
                fonts.scss
                variables.scss
            global
                fonts.scss
            utils
                mixins.scss
                functions.scss
```

**Comment by LionOnTheWeb** [comment]
Will finish this in a few hours, getting some sleep
CC: @Reaper-X @Putipaste

**Comment by Reaper-X** [comment]
@LionOnTheWeb I began work on it earlier this morning. I'll get back to it after chores all morning haha.

**Comment by LionOnTheWeb** [comment]
@Reaper-X what are you talking about? I'm almost done already 😂

**Comment by Reaper-X** [comment]
> @Reaper-X what are you talking about? I'm almost done already 😂 

Damnit I was learning about the preprocessing more too haha

**Comment by LionOnTheWeb** [comment]
@Reaper-X handing it off to you
